import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from '../components/ui/sidebar'
import { AppSidebar } from "./_components/AppSidebar"
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import Header from "./_components/Header";
import FloatingDock from "../components/ui/FloatingDock";
import { Compass, GalleryHorizontalEnd, Home as HomeIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            <Provider>
              {children}
              <Header />
              {/* Floating Dock for Home, Discovery & Library */}
              <FloatingDock
                items={[
                  {
                    title: "Home",
                    icon: <HomeIcon className="h-full w-full" />,
                    href: "/",
                  },
                  {
                    title: "Discovery",
                    icon: <Compass className="h-full w-full" />,
                    href: "/discover",
                  },
                  {
                    title: "Library",
                    icon: <GalleryHorizontalEnd className="h-full w-full" />,
                    href: "/lib",
                  },
                ]}
              />
            </Provider>

        </SidebarProvider>

      </body>
    </html>
    </ClerkProvider>

  );
}
