name: Bi-Weekly Blog Scraper

# --- TRIGGERS ---

on:
 
  workflow_dispatch:

  schedule:
   #3 am, every 15th day
    - cron:  '0 3 1,15 * *'

# --- JOBS ---

jobs:

  scrape-blogs:

    runs-on: ubuntu-latest


    steps:

      - name: Check out repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # Step 4: Install project dependencies using Poetry
      - name: Install dependencies

        run: |
          cd backend
          poetry install --only=main --no-root
      
      # Step 5: Run the scraper script
      - name: Run Python Scraper

        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON: ${{ secrets.SUPABASE_ANON }}
        # Run the script from within the backend folder
        run: |
          cd backend
          poetry run python scraper.py